#!/bin/env python
# Copyright 2010 Robert Spanton <rspanton@zepler.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import os, sys, subprocess, shutil, stat, entities, config
from entities import Elf, InstalledRpm, get_elf_libs

if len(sys.argv) < 3:
    print "Usage: %s CONFIG_FILE OUTPUT_DIR" % (os.path.basename(sys.argv[0]))
    sys.exit(1)

CONFIG_FILE = sys.argv[1]
DIRN = sys.argv[2]

if os.path.exists(DIRN):
    print "Target directory \"%s\" already exists." % DIRN
    print "Cowardly refusing to overwrite it."
    sys.exit(1)

conf = config.Config(CONFIG_FILE)

os.makedirs( DIRN )
BINDIR = os.path.join( DIRN, "bin" )
os.mkdir( BINDIR )
LIBDIR = os.path.join( DIRN, "lib" )
os.mkdir( LIBDIR )

# Dynamic linker:
shutil.copy( "/lib/ld-linux.so.2", LIBDIR )

script_dir = os.path.dirname( os.path.abspath(__file__) )

if conf.use_audit:
    "Include libaudit"
    shutil.copy( os.path.join( script_dir, "libaudit.so" ), LIBDIR )

# Fakechroot
FAKEROOT_LIB="/usr/lib/fakechroot/libfakechroot.so"
if not os.path.exists( FAKEROOT_LIB ):
    print "Error: libfakechroot.so not found on your system."
    print "You need to install it."
    print "On Fedora, it's in the fakechroot-libs package."
    print "Or you can download it from http://fakechroot.alioth.debian.org/"
    sys.exit(1)

shutil.copy( FAKEROOT_LIB , LIBDIR )

ents = []
files = set()

for rp in conf.rpms:
    ents.append( InstalledRpm(rp) )

for fname in conf.files:
    ents.append( Elf(fname) )

for ent in ents:
    for f in ent.get_files():
        files.add(f)

    ent.add_extras(DIRN)

for f in files:
    dest = os.path.join( DIRN, f.dest )

    destdir = os.path.dirname(dest)
    if not os.path.isdir( destdir ):
        os.makedirs( destdir )

    if os.path.isdir(f.source):
        if not os.path.exists(dest):
            os.makedirs(dest)
    else:
        try:
            shutil.copy( f.source, dest )
        except IOError:
            print "Warning: Couldn't read \"%s\" -- ignoring." % f.source

    if f.perms != None:
        os.chmod( dest, f.perms )

def is_elf(path):
    f = subprocess.Popen( "file -b %s" % path,
                          shell = True,
                          stdout = subprocess.PIPE )
    so, se = f.communicate()
    assert( f.wait() == 0 )

    if "ELF" in so and "executable" in so:
        if "statically" in so:
            print "Warning: \"%s\" is statically linked" % path
            return False

        return True
    return False

def write_wrapper(wrapper_path):
    shutil.copy( os.path.join( script_dir, "wrap" ), wrapper_path )

def wrap_binary(path):
    assert( path[:len(DIRN)] == DIRN )
    abspath = path[len(DIRN):]

    # Move the binary into /wrap${abspath}
    wrap_dir = os.path.join( DIRN, "wrap" )
    wrap_dir = "%s%s" % (wrap_dir, os.path.dirname(abspath))

    if not os.path.exists(wrap_dir):
        os.makedirs(wrap_dir)

    shutil.move(path, wrap_dir)
    write_wrapper( path )

def proc_dir(arg, dirname, names):
    assert "/wrap" not in dirname

    for name in names:
        fullpath = os.path.join(dirname, name)

        if is_elf( fullpath ):
            # Add any missing libraries:
            for lib in get_elf_libs(fullpath):
                libp = "%s%s" % (DIRN, lib)

                libdir = os.path.dirname(libp)
                if not os.path.exists(libdir):
                    os.makedirs(libdir)

                if not os.path.exists(libp):
                    shutil.copy(lib, libp)

            # Wrap it up!
            wrap_binary(fullpath)

# Now iterate through all files, and wrap executable elves up in 
# a blanket of fakechroot
os.path.walk( DIRN, proc_dir, None )

conf_fname = os.path.join( DIRN, "dynpk.config" )
f = open( conf_fname, "w" )
f.write( """#File automatically made by dynpk

# Fakechroot stuff
FAKECHROOT_BASE=$FAKECHROOT_BASE
LD_PRELOAD=libfakechroot.so
FAKECHROOT_EXCLUDE_PATH=/home:/tmp:/dev

LD_LIBRARY_PATH=$FAKECHROOT_BASE/lib:$FAKECHROOT_BASE/usr/lib
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
""" )

if conf.use_audit:
    f.write( """# Auditing
#AUDIT_PREFIX=$FAKECHROOT_BASE
#LD_AUDIT=libaudit.so""" )

f.write( """PS1=[FAKECHROOT@\h \W]\$\n""" )
f.close()

f = open( os.path.join( DIRN, ".fakechroot-base" ), "w" )
f.write("Base of fakeroot tree");
f.close()
